export const projectList = [
  {
    projectTitle: 'Last Stop Shop',
    projectDescription: 'Description of project',
    projectImage: '/lastStopShop.webp',
    projectImageUrl: '/lastStopShop.webp',
    projectUrl: 'https://react-shopping-cart-4ft.pages.dev/',
    projectSourceCode: 'https://github.com/marefpceo/react-shopping-cart',
    techStack: ['React', 'Vite', 'CSS'],
  },
  {
    projectTitle: 'Express Inventory App',
    projectDescription: 'Express Inventory App is an inventory management web application designed for a fictitious grocery store. The app makes use of CRUD methods for managing, maintaining and updating the store\'s inventory. The app aims to give users a quick and efficient way view and manage inventories, organizing items by categories and subcategories',
    projectImage: '/expressInventoryApp.webp',
    projectImageUrl: '/expressInventoryApp.webp',
    projectUrl: '#',
    projectSourceCode: 'https://github.com/marefpceo/express-inventory-app-v2',
    techStack: ['NodeJS', 'ExpressJS', 'PostgreSQL', 'EJS'],
  },
  {
    projectTitle: 'Blog API (Client)',
    projectDescription: 'Blog API is a project used to create a blog site using an API only backend and two different front-ends for accessing and editing blog posts.',
    projectImage: '/blogClientHome.webp',
    projectImageUrl: '/blogClientHome.webp',
    projectUrl: 'https://blog-api-c9w.pages.dev/',
    projectSourceCode: 'https://github.com/marefpceo/blog-api',
    techStack: ['React', 'Vite', 'Tailwind', 'ExpressJS'],
  },
  {
    projectTitle: 'Blog API (Admin)',
    projectDescription: 'Blog API is a project used to create a blog site using an API only backend and two different front-ends for accessing and editing blog posts.',
    projectImage: '/blogAdminLogin.webp',
    projectImageUrl: '/blogAdminLogin.webp',
    projectUrl: 'https://blog-api-admin.pages.dev/login',
    projectSourceCode: 'https://github.com/marefpceo/blog-api',
    techStack: ['React', 'Vite', 'Tailwind', 'ExpressJS'],
  },
  {
    projectTitle: 'mChat Messaging',
    projectDescription: 'Messaging app TOP',
    projectImage: '/mchatLogo.webp',
    projectImageUrl: '/messagingHome.webp',
    projectUrl: '#',
    projectSourceCode: 'https://github.com/marefpceo/messaging-app-server',
    techStack: ['NodeJS', 'ExpressJS', 'PostgreSQL', 'Prisma ORM'],
  }
];
